#ifndef MODELS_SHADOW_SYS_DESCRIPTOR_HACK_HEADER_GUARD
#define MODELS_SHADOW_SYS_DESCRIPTOR_HACK_HEADER_GUARD

#define MAX_DESCRIPTORS 10

extern int curr_descriptor;
extern int* descriptor_array[MAX_DESCRIPTORS];

#endif /*MODELS_SHADOW_SYS_DESCRIPTOR_HACK_HEADER_GUARD*/
